name: Compile NoScreenCap
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: master
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Create builds directory
        run: |
          mkdir -p builds/x64
          mkdir -p builds/x86
        shell: pwsh
      - name: Build solution for x64
        run: |
          msbuild NoScreenCap.sln /p:Configuration=Release /p:Platform=x64
      - name: Build solution for x86
        run: |
          msbuild NoScreenCap.sln /p:Configuration=Release /p:Platform=x86
      - name: Zip builds directory
        run: |
          Compress-Archive -Path D:\a\* -DestinationPath D:\a\builds.zip
        shell: pwsh
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: builds.zip
          path: D:\a\builds.zip
