name: Compile NoScreenCap
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: master
      - name: Create builds directory
        run: |
          mkdir -p builds/x64
          mkdir -p builds/x86
        shell: pwsh
      - name: Build solution for x64
        run: |
          msbuild NoScreenCap.sln /p:Configuration=Release /p:Platform=x64
      - name: Copy x64 binaries using dynamic paths
        run: |
          $console_x64_path = msbuild console\console.vcxproj /t:_GetTargetPath /p:Configuration=Release /p:Platform=x64 /v:quiet
          Copy-Item $console_x64_path -Destination "builds/x64\console.exe"
          $gui_x64_path = msbuild gui\gui.vcxproj /t:_GetTargetPath /p:Configuration=Release /p:Platform=x64 /v:quiet
          Copy-Item $gui_x64_path -Destination "builds/x64\gui.exe"
        shell: pwsh
      - name: Build solution for Win32
        run: |
          msbuild NoScreenCap.sln /p:Configuration=Release /p:Platform=Win32
      - name: Copy Win32 binaries using dynamic paths
        run: |
          $console_win32_path = msbuild console\console.vcxproj /t:_GetTargetPath /p:Configuration=Release /p:Platform=Win32 /v:quiet
          Copy-Item $console_win32_path -Destination "builds/x86\console.exe"
          $gui_win32_path = msbuild gui\gui.vcxproj /t:_GetTargetPath /p:Configuration=Release /p:Platform=Win32 /v:quiet
          Copy-Item $gui_win32_path -Destination "builds/x86\gui.exe"
        shell: pwsh
      - name: Zip builds directory
        run: |
          Compress-Archive -Path builds\* -DestinationPath builds.zip
        shell: pwsh
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: builds
          path: builds/
